VERSION="2.4.1"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
  "GDIQVCDRIJU6DWH4KJCU4UEXY3RICOYKPGBHU3HQYKAULNCYNVTQUACK",
  "GADQF4MGVZT4XSLEEZPCQ4QPIXSMFMUXWOY4KTFNIPZQO73T4HFQUACK"
]

[DOCUMENTATION]
ORG_NAME="DorkBucks"
ORG_URL="https://dorkbucks.cc"
ORG_DESCRIPTION="If it looks like a dork, walks like a dork, and quacks like a dork, it is a dork"
ORG_GITHUB="dorkbucks"
ORG_TWITTER="dorkbucks"

[[PRINCIPALS]]
name="Rubber T. Dork"
github="itsrubberdork"
twitter="rubberdork"

[[CURRENCIES]]
code="DORK"
issuer="GDIQVCDRIJU6DWH4KJCU4UEXY3RICOYKPGBHU3HQYKAULNCYNVTQUACK"
name="DorkBucks"
desc="If it looks like a dork, walks like a dork, and quacks like a dork, it is a dork"
